# Generated by Django 4.2.13 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("sales_qty", models.IntegerField()),
            ],
        ),
    ]
